name: Run Unit Tests

on:
  push:
    branches:
      - 'feature-*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.0'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Extrach Test Range
      run: output=$(python3 utils/parse_branch_name.py)
           read app_name tc_name <<< $output

    - name: Run tests
      run: python3 manage.py test ${app_name}.tests.${tc_name}