name: Print branch name on pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    example-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Run a script
          run: echo "This runs on pull requests from branches starting ${{ github.head_ref }}."
  