on: push

jobs:
    example-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Run a script
          if: startsWith(github.head_ref, 'feature-')
          run: echo "This runs on pull requests from branches starting with feature- to branch b."
  